---
- name: Nautobot Webhook interface update
  hosts: "{{ device_id }}"
  gather_facts: no
  connection: network_cli
  # become: true
  
  roles:
  - { role: updates_from_nautobot/physical_port_update }