#### Arista
- name: Arista adding IP address
  arista.eos.eos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'created'
    - ansible_network_os == 'eos'

- name: Arista removing IP address
  arista.eos.eos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
    state: deleted
  when:
    - event == 'deleted'
    - ansible_network_os == 'eos'

#### Juniper
- name: Juniper adding IP address
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
    state: overridden
  when:
    - event == 'created'
    - event == 'updated'
    - ansible_network_os == 'junos'

- name: Juniper removing IP address
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
    state: deleted
  when:
    - event == 'deleted'
    - ansible_network_os == 'junos'