#### Cisco
- name: Cisco adding IP address on {{ interface_id }}
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ address }} {{ mask }}"
    state: replaced
  when:
    - event == 'created'
    - family == '4'
    - ansible_network_os == 'ios'

- name: Cisco updating IP address on {{ interface_id }}
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ address }} {{ mask }}"
    state: replaced
  when:
    - event == 'updated'
    - family == '4'
    - ansible_network_os == 'ios'

- name: Cisco updating IP address on {{ interface_id }}
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
    state: deleted
  when:
    - event == 'delete'
    - ansible_network_os == 'ios'

#### Arista
- name: Arista adding IP address on {{ interface_id }}
  arista.eos.eos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'created'
    - ansible_network_os == 'eos'

- name: Arista updating IP address on {{ interface_id }}
  arista.eos.eos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'updated'
    - ansible_network_os == 'eos'

#### Juniper
- name: Juniper creating IP address on {{ interface_id }}
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'created'
    - ansible_network_os == 'junos'

- name: Juniper updating IP address on {{ interface_id }}
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'updated'
    - ansible_network_os == 'junos'