#### Arista
- name: Arista adding IP address on {{ interface_id }}
  arista.eos.eos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'created'
    - ansible_network_os == 'eos'

- name: Arista updating IP address on {{ interface_id }}
  arista.eos.eos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
  when:
    - event == 'updated'
    - ansible_network_os == 'eos'

#### Juniper
- name: Juniper creating IP address on {{ interface_id }}
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
    state: overridden
  when:
    - event == 'created'
    - ansible_network_os == 'junos'

- name: Juniper updating IP address on {{ interface_id }}
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ interface_id }}"
        ipv4:
          - address: "{{ ipv4_address }}"
    state: overridden
  when:
    - event == 'updated'
    - ansible_network_os == 'junos'