---
all:
  children:
    pod1:
      children:
        routers:
          hosts:
            pod1r1:
                ansible_host: 192.168.4.17
                ansible_network_os: ios
                ansible_ssh_common_args: -oKexAlgorithms=+diffie-hellman-group1-sha1
                ansible_connection: ansible.netcommon.network_cli
        core_switches:
          hosts:
            pod1sw1:
              ansible_host: 192.168.4.18
              ansible_network_os: ios
              ansible_ssh_common_args: -oKexAlgorithms=+diffie-hellman-group1-sha1
              ansible_connection: ansible.netcommon.network_cli
            pod1sw2:
              ansible_host: 192.168.4.19
              ansible_network_os: ios
              ansible_ssh_common_args: -oKexAlgorithms=+diffie-hellman-group1-sha1
              ansible_connection: ansible.netcommon.network_cli
        access_switches:
          hosts:
            pod1sw3:
              ansible_host: 192.168.4.20
              ansible_network_os: ios
              ansible_ssh_common_args: -oKexAlgorithms=+diffie-hellman-group1-sha1
              ansible_connection: ansible.netcommon.network_cli
          
              
